// Single English copy source for the landing page and the editor shell.
// The app is intentionally monolingual: there is no locale switcher and no
// locale dictionaries to keep in sync.
export const strings = {
  images: "Images",
  upload: "Upload Images",
  addtext: "Add Text",
  download: "Download PNG",
  sectors: [
    "YOUR PHOTO",
    "FAME",
    "FAMILY",
    "WEALTH",
    "KNOWLEDGE",
    "CAREER",
    "TRAVEL",
    "KIDS & CREATIVITY",
    "LOVE",
  ],
  ttDelete: "Delete",
  ttCopy: "Copy",
  ttForward: "Forward",
  ttBackward: "Backward",
  ttBold: "Bold",
  ttItalic: "Italic",
  ttUnderline: "Underline",
  ttColor: "Text color",
  ttFont: "Font",
  defaultText: "Dream",
  backHome: "Back",
  saveIdle: "Draft stays in this browser",
  saveSaving: "Saving draft...",
  saveSaved: "Draft saved",
  saveError: "Draft could not be saved",
  rotateHintTitle: "Landscape gives you more room",
  rotateHintText: "Rotate your phone to work with the canvas more easily.",
  rotateHintDismiss: "Close the rotation hint",

  landingHero: "Create your vision board for free",
  landingGo: "Go",
  landingWhatTitle: "What is a vision board?",
  landingWhatText:
    "A vision board is a powerful tool for visualizing your goals across life areas. You choose images that resonate with you — and that can dramatically increase the odds of making your goals real.",
  landingRulesTitle: "Rules for creating a vision board",
  landingRules: [
    "Bring a good mood with you — it helps you catch the right vibe",
    "Place your current favorite photo in the center — one that feels pleasant and connected to happiness, success, wealth, luxury, or love",
    "Write wishes specifically with numbers and facts, in affirmative form as if it already happened (no “not”). For example: my income is $10,000/month, I have 10,000 Instagram followers, etc.",
    "Your wishes should be achievable within the time period you're making the board for",
    "An optimal horizon is 1–3 years — that's realistically enough time to make many wishes come true",
    "Add at least one wish that will come true very soon (a planned trip, a big purchase, etc.). This signals your brain that the mechanism works",
    "Near your photo in the center you can add a foundational caption. For example: My 2026",
    "You can also add captions to images that aren't obvious. For example: clear skin, C1-level English, etc.",
  ],
  landingFinalTitle: "It's time to make dreams come true",
  donateTitle: "Support the project",
  donateText: [
    { type: "text", value: "If this editor was helpful — tips are welcome." },
    { type: "br" },
    { type: "br" },
    {
      type: "text",
      value: "Feedback and ideas for improvements: send me a DM on ",
    },
    {
      type: "link",
      href: "https://instagram.com/ks_aquila",
      text: "instagram.com/ks_aquila",
    },
    { type: "text", value: ". Thank you ❤️" },
    { type: "br" },
    { type: "br" },
    { type: "text", value: "May everything you've envisioned come true ✨" },
  ],
  donateCta: "Leave a tip",
};
