server {
    listen 80;
    listen [::]:80;
    server_name dreamboard.ks-design.art;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
    }

    location / {
        return 301 https://dreamboard.ks-design.art$request_uri;
    }
}
